[color-theme]
name = "Alabaster"
color-preference = "light"

[color-theme.base]
white = "#F7F7F7"
black = "#000000"
grey = "#777777"
blue = "#325CC0"
red = "#AA3731"
yellow = "#FFBC5D"
green = "#448C27"
purple = "#7A3E9D"
cyan = "#7A3E9D"
magenta = "#7A3E9D"
orange = "#FFBC5D"

[color-theme.syntax]
comment = "$red"

constant = "$magenta"
type = "$blue"
typeAlias = "$blue"
number = "$magenta"
enum = "$blue"
struct = "$blue"
structure = "$blue"
interface = "$blue"
attribute = "$black"
constructor = "$black"

function = "$blue"
method = "$black"
"function.method" = "$blue"

keyword = "$black"
selfKeyword = "$black"

symbol = "$black"
field = "$black"
property = "$black"
enumMember = "$black"
enum-member = "$black"
"variable.other.member" = "$black"

string = "$green"

"type.builtin" = "$blue"
builtinType = "$blue"
escape = "$grey"
embedded = "$grey"

[color-theme.ui]
"lapce.border" = "#d0d7de"
"lapce.button.primary.background" = "$white"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "$black"
"lapce.error" = "$red"
"lapce.icon.active" = "$grey"
"lapce.icon.inactive" = "#5C6370"
"lapce.plugin.author" = "$grey"
"lapce.plugin.description" = "$grey"
"lapce.plugin.name" = "$grey"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$white"
"lapce.tab.active.foreground" = "$black"
"lapce.tab.active.underline" = "$orange"
"lapce.tab.inactive.background" = "$white"
"lapce.tab.inactive.foreground" = "$grey"
"lapce.tab.inactive.underline" = "$white"
"lapce.tab.separator" = "#d0d7de"
"lapce.warn" = "$yellow"

"terminal.background" = "#f6f8fa"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "#528BFF"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "#555555"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

"editor.background" = "$white"
"editor.caret" = "#007ACC"
"editor.current_line" = "#f0f0f0"
"editor.dim" = "#5C6370"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#BFDBFE"
"editor.foreground" = "#000000"
"editor.indent_guide" = "#EEEEEE"
"editor.link" = "$blue"
"editor.selection" = "#BFDBFE"
"editor.visible_whitespace" = "$grey"

"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"

"palette.background" = "$white"
"palette.current.background" = "#eaedf0"
"palette.current.foreground" = "$grey"
"palette.foreground" = "$grey"

"completion.background" = "$white"
"completion.current" = "#eaedf0"

"hover.background" = "$grey"

"activity.background" = "#f6f8fa"
"activity.current" = "#eaedf0"

"panel.background" = "$white"
"panel.foreground" = "$black"
"panel.current" = "#BFDBFE"
"panel.current.background" = "#d0d7de"
"panel.current.foreground" = "$black"
"panel.hovered" = "#BFDBFE"
"panel.hovered.background" = "#d0d7de"
"panel.hovered.foreground" = "$black"

"status.background" = "$white"
"status.foreground" = "#777777"
"status.modal.insert" = "$red"
"status.modal.normal" = "#528BFF77"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"

"markdown.blockquote" = "#898989"