name = "alabaster-theme"
display-name = "Alabaster"
description = "Tonsky's Alabaster theme for Lapce"
version = "0.1.0"
author = "SimY4"
repository = "https://github.com/SimY4/lapce-alabaster-theme"
color-themes = ["alabaster.toml"]
icon = "alabaster.png"